### ISSUE TITLE
Changs are not reflect

### ISSUE THREAD

**Issue by RajeshZwt** [marshmallow-packages/nova-styling#138]
Installed laravel 9 and Nova 4.

And Installed marshmallow/nova-styling after running artisan optimize.
but changes are not reflected in nova admin it shows default nova admin.

thanks

**Comment by LTKort** [comment]
@RajeshZwt This package is made for Nova 3, what are you trying to achieve / customize?

**Comment by RajeshZwt** [comment]
@LTKort 

Thanks for your response. 

I need it on Nova 4. 
Is there any update for the same? 

thanks

**Comment by LTKort** [comment]
@RajeshZwt  What do you mean the same? 
Have you checked the new docs of Nova 4? There are a lot of new customization options [https://nova.laravel.com/docs/4.0/installation.html#customization](https://nova.laravel.com/docs/4.0/installation.html#customization)

You can change the branding colors, add a logo, change the footer, light / dark support. All the features of the package are now directly featured in Nova

**Comment by RajeshZwt** [comment]
@LTKort 

Yes, thank you for your support. 
I have customized using CSS.
