### ISSUE TITLE
Check if we can update TinyMCE styling in Dark Mode

### ISSUE THREAD

**Issue by stefvanesch** [marshmallow-packages/nova-styling#23]
<img width="1105" alt="Screenshot 2021-01-25 at 12 23 22" src="https://user-images.githubusercontent.com/46725619/105699817-41029f00-5f08-11eb-9f90-c0717d722108.png">

**Comment by LTKort** [comment]
See https://github.com/marshmallow-packages/nova-tinymce/issues/8
