### ISSUE TITLE
Icon Colors zijn verwarrend

### ISSUE THREAD

**Issue by stefvanesch** [marshmallow-packages/nova-styling#29]
De icons van resources die je hebt bekeken worden een andere kleur sinds de laatste update. Dit is erg verwarrend om te zien. Verder is het super nice hoe de links nu gekleurd worden, maar dit moet wel aangepast worden.

<img width="1415" alt="Screenshot 2021-01-26 at 09 37 47" src="https://user-images.githubusercontent.com/46725619/105820833-5df7aa80-5fba-11eb-89af-79dcbd691b63.png">

**Comment by LTKort** [comment]
#30 <- Opgelost
