### ISSUE TITLE
Footer.

### ISSUE THREAD

**Issue by philipbaginski** [marshmallow-packages/nova-styling#36]
I would like to have sticky footer. Any idea how to do it?

**Comment by stefvanesch** [comment]
@philipbaginski sorry for the delay. We didn't see your issue. Did you find a way to make this work or do you need some help working this out?

**Comment by philipbaginski** [comment]
I need help.

**Comment by stefvanesch** [comment]
@philipbaginski what does your footer look like? Are you using the default Nova footer? Could you provide some context. Maybe a screenshot or code example.

**Comment by philipbaginski** [comment]
I have default Nova footer.

**Comment by LTKort** [comment]
@philipbaginski Do you mean the footer `by Marshmallow © 2021·
Theme v1.6.1 · Laravel Nova v3.22.0`
Or do you mean the buttons etc.?

**Comment by philipbaginski** [comment]
I have to check it. But as I remember it's does not matter. With any footer it's the same.

**Comment by LTKort** [comment]
@philipbaginski We want to help you, can you please show a screenshot and/or example of what you to achieve?

**Comment by philipbaginski** [comment]
> @philipbaginski We want to help you, can you please show a screenshot and/or example of what you to achieve?

So, your footer from vendor/marshmallow/nova-styling/resources/views/partials/footer.blade.php looks like:

<p class="mt-8 text-center text-xs text-80">
    <a href="{{ config('app.url') }}" class="text-secondary dim no-underline">{{ config('app.name') }}</a> {{ __('by') }} <a href="https://marshmallow.dev" class="text-primary dim no-underline">Marshmallow</a> &copy; {{ date('Y') }}<span class="px-1">&middot;</span>
</p>    <p class="mt-1 text-center text-xs text-80">

    {{ __('Theme') }} v{{ \Marshmallow\NovaStyling\Theme::version() }}
    <span class="px-1">&middot;</span>
    Laravel Nova v{{ \Laravel\Nova\Nova::version() }}
</p>
{{-- <nova-dark-theme-toggle></nova-dark-theme-toggle> --}}
<nova-dark-theme-toggle label="{{ __('Dark Theme') }}"></nova-dark-theme-toggle>

, and my footer from resources/views/vendor/nova/partials/footer.blade.php looks like:

<p class="mt-8 text-center text-xs text-80">
    <a href="{{ config('app.url') }}" class="text-secondary dim no-underline">{{ config('app.name') }}</a> {{ __('...') }} <a href="#" target="_blank" rel="noopener noreferrer" class="text-primary dim no-underline">...</a> &copy; {{ date('Y') }}
</p>    <p class="mt-1 text-center text-xs text-80">
    ...........
    <br>
    ... v{{ \Laravel\Nova\Nova::version() }}
</p>
{{-- <nova-dark-theme-toggle></nova-dark-theme-toggle> --}}
<nova-dark-theme-toggle label="{{ __('Dark Theme') }}"></nova-dark-theme-toggle>

Both footers have a problem to by sticky to the botom.
