### ISSUE TITLE
Changing the red color everywhere

### ISSUE THREAD

**Issue by sirhB** [marshmallow-packages/nova-styling#37]
I am able to change the color of the sidebar but I am unable to change the red highlight on the buttons and the dark mode toggle. Where can I edit this? I am looking to use a class from a helper function, so the solution can't be editing the css.

**Comment by stefvanesch** [comment]
Its not really clear to me what you want to achieve. Could you maybe provide an example? We will update the package asap if we understand what you need.

**Comment by sirhB** [comment]
This theme makes the sidebar red, the loading animation red, the a:hover red, etc. I would like to change the red to a variable color by adding a class to the aforementioned elements.

**Comment by sirhB** [comment]
@stefvanesch Are you able to point me in the right direction?

**Comment by stefvanesch** [comment]
@LTKort Please check the comments above

**Comment by LTKort** [comment]
@sirhB  Do you mean to change the color (in this case 'red') with a class or a config? So that the color of theme is adjustable?

**Comment by sirhB** [comment]
@LTKort yes, exactly. I use tailwind, and I have a helper function that fetches a color from the database. The functions returns something like "blue-600".

If I want to make a string of text blue, I'd add the class "text-{{ setting('color') }}" to that element. If I wanted a blue background, I'd add the class "bg-{{ setting('color') }}" to that element.

**Comment by stefvanesch** [comment]
@LTKort
